name: Report | 举报
description: 举报玩家违规行为
title: "[Report 举报]: "
labels: ['🚨 Report | 举报']
assignees:
  - juzijun233
body:
  - type: input
    id: report-id
    attributes:
      label: Your Minecraft ID ｜ 你的游戏ID
      description: 填写你的游戏ID
      placeholder: ex. juzijun233 例如 juzijun233
    validations:
      required: true
  - type: dropdown
    id: server
    attributes:
      label: Server/Mode ｜ 服务器/模式
      description: Which Server or gamemode 发生在哪个服务器或游戏模式
      options:
        - Lobby 大厅
        - Classic survival 经典生存
    validations:
      required: true
  - type: dropdown
    id: report-type
    attributes:
      label: 报告类型
      description: 你要报告什么？
      options:
        - Spam 广告、刷屏、垃圾信息
        - Cheat 作弊或黑客行为
        - Lost 丢失
        - Theft 失窃
        - Destroyed 被破坏
        - Malicious kill 恶意击杀
        - Bad information (verbal, skin, or other) 不良信息（言语、皮肤或其他）
    validations:
      required: true
  - type: markdown
    attributes:
        value: |
            👉 不同的报告类型需要提交的信息略有不同
  - type: textarea
    id: repro-more-info
    attributes:
      label: More info ｜ 内容补充
      description: "内容补充"
      value: |
        1.
        2.
        3.
        ...
        损失了什么物品、方块或生物等
        或认为对方违反了什么规则/疑似使用了什么作弊
        亦可描述事件经过
        提供尽可能准确的时间、提供尽可能准确的位置
        例子：丢失了 X数量的Y物品；少了X数量的Y生物；位于X位置的方块被破坏
      render: bash
    validations:
      required: true
