name: Report | 举报
description: 举报玩家违规行为
title: "[Report 举报]: "
labels: ['🚨 Report | 举报']
assignees:
  - juzijun233
body:
  - type: input
    id: report-id
    attributes:
      label: Your Minecraft ID 你的游戏ID
      description: 填写你的游戏ID
      placeholder: ex. juzijun233 例如 juzijun233
    validations:
      required: true
  - type: dropdown
    id: server
    attributes:
      label: Server/Mode 服务器/模式
      description: Which Server or gamemode 发生在哪个服务器或游戏模式
      options:
        - Lobby 大厅
        - 经典生存
    validations:
      required: true
  - type: dropdown
    id: report-type
    attributes:
      label: 报告类型
      description: 你要报告什么？
      options:
        - Spam 广告、刷屏、垃圾信息
        - Cheat 作弊或黑客行为
        - Lost 丢失
        - Theft 失窃
        - Destroyed 被破坏
        - Malicious kill 恶意击杀
        - Bad information (verbal, skin, or other) 不良信息（言语、皮肤或其他）
    validations:
      required: true
  - type: markdown
    attributes:
        value: |
            👉 不同的报告类型需要提交的信息略有不同
  - type: checkboxes
    id: report-hack-type
    attributes:
      label: 您认为对方使用了什么类型的外挂？
      description: 选择你看上去疑似的
      options:
        - label: 非法飞行
        - label: 杀戮光环
        - label: 快速食用
        - label: 飞船
        - label: 无击退
        - label: 其它
  - type: textarea
    id: repro-more-info
    attributes:
      label: Reproduction steps
      description: "内容补充"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
